---

- name: Ensure libselinux-python is installed
  yum: name=libselinux-python

- name: Install EPEL repo
  yum: name=epel-release state=present

- name: Install dependencies
  yum: name={{item}}
  with_items:
    - cronie
    - gzip
    - python-boto
    - s3cmd

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}-{{backup_duplicity_version}}"
  when: backup_duplicity_version

- name: Install duplicity
  yum: name={{backup_duplicity_pkg}}
